//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/chinmaykelkar/Code/Harrisburg/Theory of Computation/FinalProject/FinalProject/conditionalstatements.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class conditionalstatementsLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		PRINT=1, IS=2, IF=3, ELSE=4, EQUALS=5, ID=6, NUMBER=7, WHITESPACE=8;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"PRINT", "IS", "IF", "ELSE", "EQUALS", "ID", "NUMBER", "WHITESPACE"
	};


	public conditionalstatementsLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public conditionalstatementsLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'print'", "'is'", "'if'", "'else'", "'=='"
	};
	private static readonly string[] _SymbolicNames = {
		null, "PRINT", "IS", "IF", "ELSE", "EQUALS", "ID", "NUMBER", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "conditionalstatements.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static conditionalstatementsLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\n', '\x35', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x6', '\a', ')', '\n', 
		'\a', '\r', '\a', '\xE', '\a', '*', '\x3', '\b', '\x6', '\b', '.', '\n', 
		'\b', '\r', '\b', '\xE', '\b', '/', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x2', '\x2', '\n', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x3', 
		'\x2', '\x5', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', 
		';', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\x36', 
		'\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x3', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x19', '\x3', '\x2', '\x2', '\x2', '\a', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\v', '$', '\x3', '\x2', '\x2', '\x2', '\r', '(', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '-', '\x3', '\x2', '\x2', '\x2', '\x11', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x14', '\a', 'r', '\x2', '\x2', '\x14', 
		'\x15', '\a', 't', '\x2', '\x2', '\x15', '\x16', '\a', 'k', '\x2', '\x2', 
		'\x16', '\x17', '\a', 'p', '\x2', '\x2', '\x17', '\x18', '\a', 'v', '\x2', 
		'\x2', '\x18', '\x4', '\x3', '\x2', '\x2', '\x2', '\x19', '\x1A', '\a', 
		'k', '\x2', '\x2', '\x1A', '\x1B', '\a', 'u', '\x2', '\x2', '\x1B', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\a', 'k', '\x2', '\x2', '\x1D', 
		'\x1E', '\a', 'h', '\x2', '\x2', '\x1E', '\b', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', ' ', '\a', 'g', '\x2', '\x2', ' ', '!', '\a', 'n', '\x2', '\x2', 
		'!', '\"', '\a', 'u', '\x2', '\x2', '\"', '#', '\a', 'g', '\x2', '\x2', 
		'#', '\n', '\x3', '\x2', '\x2', '\x2', '$', '%', '\a', '?', '\x2', '\x2', 
		'%', '&', '\a', '?', '\x2', '\x2', '&', '\f', '\x3', '\x2', '\x2', '\x2', 
		'\'', ')', '\t', '\x2', '\x2', '\x2', '(', '\'', '\x3', '\x2', '\x2', 
		'\x2', ')', '*', '\x3', '\x2', '\x2', '\x2', '*', '(', '\x3', '\x2', '\x2', 
		'\x2', '*', '+', '\x3', '\x2', '\x2', '\x2', '+', '\xE', '\x3', '\x2', 
		'\x2', '\x2', ',', '.', '\t', '\x3', '\x2', '\x2', '-', ',', '\x3', '\x2', 
		'\x2', '\x2', '.', '/', '\x3', '\x2', '\x2', '\x2', '/', '-', '\x3', '\x2', 
		'\x2', '\x2', '/', '\x30', '\x3', '\x2', '\x2', '\x2', '\x30', '\x10', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\x32', '\t', '\x4', '\x2', '\x2', 
		'\x32', '\x33', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\b', '\t', 
		'\x2', '\x2', '\x34', '\x12', '\x3', '\x2', '\x2', '\x2', '\x5', '\x2', 
		'*', '/', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
